//WARNING: DO NOT EDIT OR DELETE THIS HEADER FILE!

#pragma once

#define IDW_LOGIN                      1000
#define IDC_BTN_MIN                    1001
#define IDC_BTN_CLOSE                  1002
#define IDC_EDT_NAME                   1003
#define IDC_EDT_PASSWORD               1004
#define IDC_CHK_REMEMBER_PASSWORD      1005
#define IDC_CHK_AUTO_LOGIN             1006
#define IDC_BTN_LOGIN                  1007
#define IDC_BTN_FORGET_PASSWORD        1008
#define IDC_BTN_REGISTER               1009
#define IDW_MAIN                       1010
#define IDC_BTN_SKIN                   1011
#define IDC_CHK_MAX                    1012
#define IDC_BTN_HEADER                 1013
#define IDC_CHK_STATUS                 1014
#define IDC_BTN_MAIL                   1015
#define IDC_BTN_ZONE                   1016
#define IDC_BTN_MESSAGE                1017
#define IDC_EDT_SEARCH                 1018
#define IDC_BTN_SEARCH_WEB             1019
#define IDC_RAD_FRIEND                 1020
#define IDC_RAD_GROUP                  1021
#define IDC_RAD_RECENT                 1022
#define IDC_CHK_START                  1023
#define IDC_BTN_GAME                   1024
#define IDC_BTN_SETTING                1025
#define IDC_BTN_MSG                    1026
#define IDC_BTN_SECURE                 1027
#define IDC_BTN_SEARCH                 1028
#define IDC_BTN_APP_MGR                1029
#define IDC_BTN_WEATHER                1030
#define IDC_STA_NAME                   1031
#define IDC_BTN_SIGN                   1032
#define IDC_STA_TITLE                  1033
#define IDC_TWMGR_MAIN                 1034
#define IDC_PNL_UGRID_TAB              1035
#define IDW_FRIEND_PAGE                1036
#define IDW_GROUP_PAGE                 1037
#define IDC_STA_GROUP                  1038
#define IDW_RECENT_PAGE                1039
#define IDC_STA_RECENT                 1040
#define IDW_START_MENU                 1041
#define IDW_CHAT_FRAME                 1042
#define IDC_BTN_EXIT                   1043
#define IDC_BTN_VIDEO                  1044
#define IDC_BTN_AUDIO                  1045
#define IDC_BTN_TRANS_FILE             1046
#define IDC_BTN_CREATE_GROUP           1047
#define IDC_BTN_REMOTE                 1048
#define IDC_BTN_MORE                   1049
#define IDC_CHK_FONT                   1050
#define IDC_CHK_FACE                   1051
#define IDC_BTN_SEND                   1052
#define IDC_BTN_SEND2                  1053
