//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UIShop.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_VERSION                     101
#define IDS_VERSION_CHAINLINK           102
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_UIShopTYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDR_CONTROL_PROPERTIES          133
#define ID_PROPERTIES                   135
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_PROPERTIES_WND              158
#define IDS_CONTACT_WND                 159
#define IDS_STORYBOARD_WND              160
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_CLOSETESTWINDOW             181
#define IDR_POPUP_RESOURCE              182
#define IDR_POPUP_STYLE                 183
#define IDR_PROPERTIES                  184
#define IDB_PROPERTIES_HC               185
#define IDR_CONTROLBAR                  215
#define IDR_LAYOUT                      217
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_PROJECT_FILTEREXT           307
#define IDR_PROJECT_FILTERNAME          308
#define IDD_NEWPROJECT                  310
#define IDD_TABORDER                    311
#define IDD_CLASS_WIZARD                313
#define IDD_EVENT_HANDLER_WIZARD        314
#define IDD_IMAGE_SYMBOLS               315
#define IDD_ADD_HANDLER                 316
#define IDD_TRANSFORM_DIALOG            317
#define LibUIDKSkinRcTop                321
#define LibUIDKSkinRcBottom             322
#define LibUIDKSkinRcTop_Chs            323
#define LibUIDKSkinRcBottom_Chs         324
#define IDD_GENERATE_RESOURCE           325
#define IDD_FORMAT_BRUSH                326
#define IDI_ALPHAICON                   328
#define IDD_ADD_ALL_CLASS               329
#define IDD_GENERATE_CLASS_INFO_FILE    330
#define IDD_SYNC_SKIN_TAB_ORDER         331
#define IDD_TEMPLATE_NAME               332
#define IDB_STORYPANELSLIDERBK          333
#define IDB_STORYPANELSLIDERBKD         334
#define IDB_STORYPANELRAMEFLAG          335
#define IDB_STORYPANELSLIDERTHUMB       336
#define IDC_BTN_BROWSER                 1001
#define IDC_BTN_GOTO                    1002
#define IDC_EDT_CLASS_NAME              1003
#define IDC_EDT_WINDOW_ID               1004
#define IDC_EDT_H_FILE                  1005
#define IDC_EDT_CPP_FILE                1006
#define IDC_BTN_BROWSE                  1007
#define IDC_RAD_VC6                     1008
#define IDC_RAD_VC_NET                  1009
#define IDC_CHK_GEN_HANDLER             1010
#define IDC_CHK_GEN_VARIABLE            1011
#define IDC_CHK_GEN_DO_DATA_EXCHANGE    1012
#define IDC_TREE_IMAGE_SYMBOLS          1013
#define IDC_STA_VERSION                 1014
#define IDC_TREE_MESSAGE                1015
#define IDC_RICHEDIT_CODE               1016
#define IDC_EDT_RES_SOURCE              1017
#define IDC_BTN_BROWSE_RES              1018
#define IDC_EDT_XUI_TARGET              1019
#define IDC_BTN_BROWSE_XUI              1020
#define IDC_BTN_TRANSFORM               1021
#define IDC_BTN_GO_SOURCE               1022
#define IDC_BTN_GO_TARGET               1023
#define IDC_BTN_AUTO_ADJUST             1024
#define IDC_EDT_SAVE_PATH               1025
#define IDC_CMB_LANGUAGE                1028
#define IDC_RAD_RELATE_SAVE_PATH        1029
#define IDC_RAD_RElATE_CUSTOM           1030
#define IDC_EDT_RELATE_CUSTOM           1031
#define IDC_EDT_SKIN_PATH               1032
#define IDC_EDT_RELATE_BASE_ON_SAVE_PATH 1033
#define IDC_LIST_FORMAT_BRUSH           1034
#define IDC_BTN_MOVE_TO_UNUSED          1035
#define IDC_BTN_HIGHLIGHT               1036
#define IDC_STA_COPYRIGHT               1037
#define IDC_EDT_ALL_CLASSED_SAVE_PATH   1038
#define IDC_EDT_CODE_FOLDER             1040
#define IDC_BTN_BROWSE_CODE_FOLDER      1041
#define IDC_EDT_CLASS_INFO_FILE         1042
#define IDC_BTN_BROWSE_CLASS_INFO_FILE  1043
#define IDC_EDT_SKIN_SOURCE             1044
#define IDC_BTN_BROWSE_SOURCE           1045
#define IDC_EDT_SKIN_TARGET             1046
#define IDC_BTN_BROWSE_TARGET           1047
#define IDC_RAD_PROJECT_GENERAL         1048
#define IDC_RAD_PROJECT_MDI             1049
#define IDC_RAD_PROJECT_IM              1050
#define IDC_RAD_PROJECT_WEISHI          1051
#define IDC_EDT_TEMPLATE_PATH           1052
#define IDC_BTN_BROWSE_TEMPLATE         1053
#define IDC_EDT_PREFIX                  1054
#define IDC_EDT_TARGET                  1055
#define IDC_CMB_MERGE_TOOL_PATH         1057
#define IDC_BTN_BROWSE_MERGE_TOOL       1058
#define IDC_BTN_MERGE                   1059
#define IDC_STA_HOME_PAGE               1060
#define IDC_STA_SOURCE_CODE             1061
#define IDC_STA_INFO                    1062
#define IDC_LST_TABORDER                1078
#define IDC_BTN_MOVEUP                  1079
#define IDC_BTN_MOVEDOWN                1080
#define IDC_RAD_VC60                    1231
#define IDC_RAD_VC71                    1232
#define IDC_RAD_VC80                    1233
#define IDC_RAD_VC90                    1234
#define IDC_RAD_VC100                   1235
#define IDC_RAD_VC110                   1236
#define IDC_RAD_VC120                   1237
#define IDC_RAD_VC140                   1238
#define IDC_EDT_PROJECTNAME             1250
#define IDC_EDT_LOCATION                1251
#define IDC_RAD_NONE                    1252
#define IDC_RAD_HEADER                  1253
#define IDC_CHK_ACTIVEX                 1254
#define IDC_CHK_SOCKET                  1255
#define IDC_RAD_YES                     1256
#define IDC_RAD_NO                      1257
#define IDSM_INSERT                     32771
#define IDSM_PROPERTIES                 32772
#define ID_VIEW_CONTROLBAR              32772
#define IDSM_TEST                       32773
#define ID_VIEW_LAYOUTBAR               32773
#define ID_FILE_NEW_LIBUIDK_PROJECT     32774
#define ID_HELP_UISHOP                  32775
#define ID_HELP_LIBUIDK                 32776
#define ID_HELP_VIDEO                   32777
#define ID_HELP_WEB_LINK                32778
#define IDSM_ADD_CLASS                  32779
#define IDSM_DELETEWINDOW               32780
#define IDSM_TABORDER                   32782
#define IDSM_FINDINHD                   32783
#define IDSM_CLOSE                      32784
#define ID_CONTROL_SELECT               32787
#define IDSM_CTRL_PROPERTIES            32788
#define ID_CONTROL_BUTTON               32788
#define ID_CONTROL_CHECKBOX             32789
#define ID_CONTROL_RADIOBUTTON          32790
#define ID_CONTROL_STATIC               32791
#define ID_CONTROL_EDIT                 32792
#define ID_CONTROL_COMBOBOX             32793
#define ID_CONTROL_SLIDER               32794
#define ID_CONTROL_SPIN                 32795
#define ID_CONTROL_PROGRESS             32796
#define ID_CONTROL_HOTKEY               32797
#define ID_CONTROL_IPADDRESS            32798
#define ID_CONTROL_SLIDEREX             32799
#define ID_CONTROL_LISTCTRL             32800
#define ID_CONTROL_TREECTRL             32801
#define ID_CONTROL_SCROLLBAREX          32802
#define ID_CONTROL_THUMBNAIL            32803
#define ID_CONTROL_TREELIST             32804
#define ID_CONTROL_RICHEDIT             32805
#define ID_CONTROL_RICHEDIT_IM          32806
#define ID_CONTROL_HTMLCTRL             32807
#define ID_CONTROL_DATETIMECTRL         32808
#define ID_CONTROL_WAVECTRL             32809
#define ID_CONTROL_PICCTRL              32810
#define ID_CONTROL_MENUBAR              32811
#define ID_CONTROL_SPLITTER             32812
#define ID_CONTROL_RECT                 32813
#define ID_CONTROL_SPLITTERWL           32814
#define ID_CONTROL_LINE                 32815
#define ID_CONTROL_TEXT                 32816
#define ID_CONTROL_BUTTONWL             32817
#define ID_CONTROL_CHECKBOXWL           32818
#define ID_CONTROL_RADIOWL              32819
#define ID_CONTROL_SLIDERWL             32820
#define ID_CONTROL_PIC                  32821
#define ID_CONTROL_RICHEDITWL           32822
#define ID_CONTROL_IMWL                 32823
#define ID_CONTROL_TASK_WND_MGR         32824
#define ID_CONTROL_DOCK_PANEL           32825
#define ID_CONTROL_UNIFORM_GRID_PANEL   32826
#define ID_CONTROL_STACK_PANEL          32827
#define ID_LAYOUT_ALIGN_LEFT            32850
#define ID_LAYOUT_ALIGN_RIGHT           32851
#define ID_LAYOUT_ALIGN_TOP             32852
#define ID_LAYOUT_ALIGN_BOTTOM          32853
#define ID_LAYOUT_CENTER_VERTICAL       32854
#define ID_LAYOUT_CENTER_HORIZONTAL     32855
#define ID_LAYOUT_SPACE_ACROSS          32856
#define ID_LAYOUT_SPACE_DOWN            32857
#define ID_LAYOUT_SAMESIZE_WIDTH        32858
#define ID_LAYOUT_SAMESIZE_HEIGHT       32859
#define ID_LAYOUT_SAMESIZE_SIZE         32860
#define ID_DESIGN_SIZE_TO_CONTENT       32861
#define ID_DESIGN_BACKGROUND_SHOW       32862
#define ID_EDIT_UNUSED_IMAGE_SYMBOLS    32863
#define ID_EDIT_UNFOUND_IMAGE_SYMBOLS   32864
#define IDSM_INSERT_RES_COLOR           32865
#define IDSM_DELETE_RESOURCE            32869
#define ID_TOOLS_CREATE_LANGUAGE_FILE   32871
#define ID_TOOLS_TRANSFORM_DIALOG       32872
#define IDSM_CTRL_ADD_HANDLER           32873
#define IDSM_INSERT_STYLE_ITEM          32875
#define IDSM_DELETE_STYLE               32876
#define ID_VIEW_SHOW_CONTROL_TYPE       32877
#define ID_VIEW_SHOW_CONTROL_ID         32878
#define ID_VIEW_SHOW_CONTROL_INDEX      32879
#define ID_TOOLS_CREATE_RESOURCE_FILE   32880
#define ID_DESIGN_FORMAT_BRUSH          32881
#define IDSM_ADD_EVENT_HANDLER_CLASS    32882
#define IDSM_ADD_ALL_EVENT_HANDLER_CLASSES 32883
#define ID_DESIGN_SIZE_TO_FOREGROUND_CONTENT 32886
#define IDSM_CONVERT_TO_CONDITION_FONT  32887
#define IDSM_INSERT_GENERAL_FONT        32888
#define IDSM_INSERT_CONDITION_FONT_CHILD 32889
#define IDSM_ADD_ALL_CLASSES            32891
#define ID_TOOLS_CREATE_CLASS_INFO_FILE 32892
#define ID_TOOLS_SYNC_SKIN_TAB_ORDER    32893
#define ID_TOOLS_RENAME_TEMPLATE_FILE   32896
#define ID_TOOLS_GENERATE_RESOURCE_H    32897
#define IDSM_TEST_CUR_FRAME             32899
#define IDSM_TEST_HIGH_DPI              32900
#define ID_INDICATOR_POS                59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32901
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           333
#endif
#endif
